#!/bin/bash
#
source ../version

build_dir=`pwd`

INSTALL_DIR=$build_dir"/build-"$_ARCH$_BITS

cd simavr/simavr

echo Building libsimavr for "${TARGET_PREFIX}"

make libsimavr RESLEASE=1 
make install RESLEASE=1 DESTDIR="${INSTALL_DIR}"

